### ISSUE TITLE
need some help?

### ISSUE THREAD

**Issue by dom-christo** [karowan/Recurring_Transaction#1]
npm run start -- --accountAddress="0x8e99ea983a9cdeaff9c48303265059b74d35029d" --password="L0n6H7t6Q1i2" --contractAddress="0x8762d6a1121be482f08cb705a6444665d2b97907" --oracleAddress="0x8762d6a1121be482f08cb705a6444665d2b97907" --jobID="4c150bbae909410b8eaeb38b72cccd4c" --providerURL="ws://10.1.0.5:8546"

receiving below

`Sending Request.
Error: Node error: {"code":-32601,"message":"Method not found"}
    at Function.validate (/home/clinkadmin/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at WebsocketProvider._callee$ (/home/clinkadmin/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:188:61)
    at tryCatch (/home/clinkadmin/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/clinkadmin/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/clinkadmin/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/clinkadmin/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/clinkadmin/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by apeppels** [comment]
Having the same issue, @karowan any idea?

**Comment by karowan** [comment]
@apeppels It looks like there is something wrong with your ws provider if you are getting this error. Unfortunately this will only work if you follow the setup exactly. If you are, like @dom-christo, using a `providerURL` that is not localhost, I'm not really sure which `ws-apis` you have enabled. Also I will update the readme to point you in the direction of doing this task correctly instead of using this script.
