### ISSUE TITLE
"Unable to lock the account" error thrown

### ISSUE THREAD

**Issue by csmile2** [karowan/Recurring_Transaction#2]
Hey @karowan great work with this node app from what I've seen so far.
I'm having an issue when running this command:
`npm run start -- --accountAddress="yourParityAddress" --password="yourPassword" --contractAddress="yourContractAddress" --oracleAddress="yourOracleAddress" --jobID="yourJobID" --providerURL="yourProviderAddress"` (of course I'm changing the variables specific to my configuration..)
And this is the error I get:
`Sending Request.
Error: Node error: {"code":-32023,"message":"Unable to unlock the account.","data":"InvalidAccount"}
    at Function.validate (/home/ec2-user/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at WebsocketProvider._callee$ (/home/ec2-user/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:188:61)
    at tryCatch (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/ec2-user/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/ec2-user/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6333) UnhandledPromiseRejectionWarning: Error: Node error: {"code":-32065,"message":"No light peers who can serve data"}
    at Function.validate (/home/ec2-user/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at WebsocketProvider._callee$ (/home/ec2-user/Recurring_Transaction/node_modules/web3-providers/dist/web3-providers.cjs.js:188:61)
    at tryCatch (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ec2-user/Recurring_Transaction/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/ec2-user/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/ec2-user/Recurring_Transaction/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)`
Does anybody else get this error too? Any help is appreciated.

**Comment by karowan** [comment]
@csmile2 From what I can tell, there is a problem with how you created the account on your parity client or the password you entered to unlock the account is incorrect.
